---
title: "Etapa 1. El contexto"
author: "Elías Alejandro Corral Rodríguez,Jesús Oscar Flores Cota,Marcelo Balderas Gómez,Omar Gael Arzaga Chaparro,Adrían David Páez Parra"
date: today
format:
  docx:
    toc: false          # Do not include table of contents

execute:
  echo: true          # Show code in the output document
---

# Exploración de la base de datos

```{r}
library(tidyverse)
library(here)

M19 <- read_csv(here("data", "Datos_molec_2019.csv"))
M20 <- read_csv(here("data", "Datos_molec_2020.csv"))
M21 <- read_csv(here("data", "Datos_molec_2021.csv"))
M22 <- read_csv(here("data", "Datos_molec_2022.csv"))
M23 <- read_csv(here("data", "Datos_molec_2023.csv"))
M24 <- read_csv(here("data", "Datos_molec_2024.csv"))

str(M19)
str(M20)
str(M21)
str(M22)
str(M23)
str(M24)
```

## Diccionarios

```{r}
Dicc19 <- read_csv(here("data", "Diccionario_molec_2019.csv"))
Dicc20 <- read_csv(here("data", "Diccionario_molec_2020.csv"))
Dicc21 <- read_csv(here("data", "Diccionario_molec_2021.csv"))
Dicc22 <- read_csv(here("data", "Diccionario_molec_2022.csv"))
Dicc23 <- read_csv(here("data", "Diccionario_molec_2023.csv"))
Dicc24 <- read_csv(here("data", "Diccionario_molec_2024.csv"))

```

## Resumen de las variables

```{r}
summary(M19)
summary(M20)
summary(M21)
summary(M22)
summary(M23)
summary(M24)
```

# Selección de las variables

```{r}
M19selec <- M19[,c(2,10:16,18,19,27,28,69,70,104,105)]
M20selec <- M20[,c(9,15:21,23,24,32,33,74,75,11,10)]
M21selec <- M21[,c(9,15:21,23,24,32,33,74,75,11,10)]
M22selec <- M22[,c(9,15:21,23,24,32,33,74,75,11,10)]
M23selec <- M23[,c(9,15:21,23,24,32,33,74,75,11,10)]
M24selec <- M24[,c(9,15:21,23,24,32,33,74,75,11,10)]

```

## Datos perdidos o faltantes

```{r}
summary(M19selec)
summary(M20selec)
summary(M21selec)
summary(M22selec)
summary(M23selec)
summary(M24selec)

```

No se presentan datos invalidos en las variables seleccionadas.

```{r}
#sum(is.na(M20selec[, 10])) / length(M20selec[, 10])
```

## Para quitar los NA's

```{r}
#M20selec <- na.omit(M20selec)
#summary(M20selec)
```

Modificación
Oscar
Omar
